IS_ERROR=0
GIT_BRANCH=''

pipeline {
    agent any

    stages {
        
        
        stage('cloning the repo') {
            steps {
                shell("git clone -b test-cf https://github.com/Shashwatsingh22/CloudFormation-Script-CI-CD")
            }
        }
        
        stage('start testing')
        {
          steps{
              catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                  script{
                      IS_ERROR = sh "bash /var/lib/jenkins/workspace/cf-check-teat/cf-test/test.sh"
                  }
                }
          }
        }
        
        stage('send error mail')
        {
            when {
             expression { IS_ERROR == 0}
            }
            steps
            {
                sh "python3 cf-test/sendMail.py error-found"
            }
        }
        
        stage('send test pass mail')
        {
            when {
             expression { IS_ERROR == false }
            }
            steps
            {
                shell('bash /var/lib/jenkins/workspace/cf-check-teat/cf-test/getDet.sh')
                shell("python3 cf-test/sendMail.py no-error-found")
            }
        }
        
        stage('push to master')
        {
            when {
             expression { IS_ERROR == false }
            }
            steps
            {
                shell("push to master")
            }
        }
    }
}
